<div className='my'>
<div className='h'>
        <h1>Maximize Yield?</h1>
</div>
<div className='inp'>
        <div className='cardc'>
            <div className='crop-image'>
            <img src={crop} />   
            <p>Select the crops to compare</p>
            </div>
            <div className = "crop_details1">
            <p>
                <Select
                onChange={handleChange}
                isMulti
                options={crops_m}
                value={crops_m.filter(obj => selectedValue.includes(obj.value))}
                className="basic-multi-select"
                classNamePrefix="select"
                />
               
            </p> 
            
            </div>
        </div> 
        <div className='card1'>
            <div className='crop-image'>
            <img src={drop} />   
            <p> Water Available(mm)</p>
            <input type="number" placeholder = "Enter the amount of water " style={{width: "175px"}} onChange = {e => setwa(e.target.value)}/>
            </div>
        </div>
</div>
<div className='myo'>
    <button className="gooey-button" onClick = {myo}>Calculate</button>
    <div className='graph'>
        <Bar
        data={state}
        options={{
            title:{
            display:true,
            fontSize:20
            },
        }}
        />
    </div>
</div>
<h4>Maximum Yield will be achieved by {myc} </h4>
</div>
<div className="sep">
<ColoredLine color="black" />
</div>
<div className='my'>
<div className='h'>
        <h1>Maximize Revenue?</h1>
</div>
<div className='inp1'>
        <div className='cardc'>
            <div className='crop-image'>
            <img src={crop} />   
            <p>Select the crops to compare</p>
            </div>
            <div className = "crop_details1">
            <p>
                <Select
                onChange={handleChange1}
                isMulti
                options={crops_m}
                value={crops_m.filter(obj => selectedValue1.includes(obj.value))}
                className="basic-multi-select"
                classNamePrefix="select"
                />
               
            </p> 
            
            </div>
        </div> 
        <div className='card1'>
            <div className='crop-image'>
            <img src={drop} />   
            <p> Water Available(mm)</p>
            <input type="number" placeholder = "Enter the amount of water " style={{width: "175px"}} onChange = {e => setwa1(e.target.value)}/>
            </div>
        </div>
        <div className='card1'>
            <div className='crop-image'>
            <img src={dollar} />   
            <p> Production cost($)</p>
            <input type="number" placeholder = "Enter the amount " style={{width: "175px"}} onChange = {e => setwa1(e.target.value)}/>
            </div>
        </div>
</div>
<div className='myo'>
    <button className="gooey-button" onClick = {mr}>Calculate</button>
    <div className='graph'>
        <Bar
        data={state1}
        options={{
            title:{
            display:true,
            fontSize:20
            },
        }}
        />
    </div>
</div>
<h4>Maximun Revenue will be generated by {mrc} </h4>
</div>
<div className="sep">
<ColoredLine color="black" />
</div>
<div className='my'>
<div className='h'>
    <h1>Maximize Water use efficiency?</h1>
</div>
<div className='inp2'>
    <div className='card1'>
        <div className='crop-image'>
        <img src={crop} />   
        <p>Select the crops to compare</p>
        </div>
        <div className = "crop_details1">
        <p>
            <Select
            onChange={(e) => handleChange2(e)}
            isMulti
            options={crops_m}
            value={crops_m.filter(obj => selectedValue2.includes(obj.value))}
            className="basic-multi-select"
            classNamePrefix="select"
            />
        
        </p> 
        
        </div>
    </div> 
    <div className='card1'>
        <div className='crop-image'>
        <img src={drop} />   
        <p> Water Available(mm)</p>
        <input type="number" placeholder = "Enter the amount of water " style={{width: "175px"}} onChange = {e => setwa2(e.target.value)}/>
        </div>
    </div>
</div>
<div className='myo'>
<button className="gooey-button" onClick = {mwe}>Calculate</button>
<div className='graph'>
    <Bar
    data={state2}
    options={{
        title:{
        display:true,
        fontSize:20
        },
    }}
    />
</div>
</div>
<h4>{mwc} maximizes the water use efficiency </h4>
</div>
<div className="sep">
<ColoredLine color="black" />
</div>